# /// script
# requires-python = ">=3.10"
# dependencies = ["pillow"]
# ///
"""Create native icon containers, checksums and the distributable brand archive."""
from pathlib import Path
from PIL import Image
from PIL.PngImagePlugin import PngInfo
import hashlib
import json
import shutil
import zipfile

ROOT = Path(__file__).resolve().parents[2]
BRAND = ROOT / "assets/brand/freebo"
config = json.loads((BRAND / "brand.json").read_text())
for job in config["rasterJobs"]:
    png = ROOT / job["output"]
    image = Image.open(png)
    image.load()
    assert image.size == (job["width"], job["height"])
    metadata = PngInfo()
    metadata.add_text("impeccable:prompt", "Origin: " + job["svg"] + ". Canonical Freebo / Atma 600 artwork rendered with Electron Chromium; generated by pnpm brand:generate.")
    image.save(png, pnginfo=metadata, optimize=True)
icon = Image.open(BRAND / "icons/icon-1024.png").convert("RGBA")
icon.save(BRAND / "icons/icon.ico", sizes=[(16,16), (24,24), (32,32), (48,48), (64,64), (128,128), (256,256)])
icon.save(BRAND / "icons/icon.icns", sizes=[(16,16), (32,32), (64,64), (128,128), (256,256), (512,512), (1024,1024)])
for source, target in [
    ("icons/icon.ico", "resources/icon.ico"), ("icons/icon.icns", "resources/icon.icns"),
    ("icons/icon-1024.png", "resources/icon.png"),
    ("icons/icon-512.png", "public/icon.png"), ("social/social.png", "docs/assets/brand/social.png"),
]:
    shutil.copyfile(BRAND / source, ROOT / target)
entries = {}
for file in sorted(BRAND.rglob("*")):
    if file.is_file() and file.name not in {"manifest.json", "Freebo-brand-kit.zip"}:
        entries[str(file.relative_to(BRAND))] = {"bytes": file.stat().st_size, "sha256": hashlib.sha256(file.read_bytes()).hexdigest()}
manifest = {"brand": "Freebo", "font": config["font"], "colors": config["colors"], "files": entries}
(BRAND / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
archive = BRAND / "Freebo-brand-kit.zip"
with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as bundle:
    for file in sorted(BRAND.rglob("*")):
        if file.is_file() and file != archive:
            info = zipfile.ZipInfo(str(file.relative_to(BRAND)), (2026,10,6,0,0,0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            bundle.writestr(info, file.read_bytes())
    readme = ROOT / "docs/brand/README.md"
    if readme.exists():
        bundle.writestr("README.md", readme.read_bytes())
print(f"Packaged {len(entries)} assets. Archive: {archive.stat().st_size / 1024:.0f} KiB.")
